### PR TITLE
Aframe primitive mappings and systems support

### PR DESCRIPTION
**Pull request by jesstelford**
This is one of many attempts I've had at getting this to work over the last week. And it still doesn't work 100%.

Let me know your thoughts on the below - any suggestions?

## Known issues
- Systems don't seem to work 100%. In particular the physics component is a bit odd. It appears to half work, starting some of the physics simulation, but the position and rotation components have values that are `NaN`. When the exact same structure is used outside of `aframe-react`, it works without problem.
- The issues go away if the inspector is opened then closed (Wha!?)

## Other attempts

- Using `debug` on the scene. Didn't appear to have any noticable effect
- Using `flushToDOM` on the ref once it was available. Also didn't seem to make much change
- Listening for the entity/scene loaded event, then using `flushToDOM`. This had a similar result to the one in this PR

## Example

The kyeboard controls component isn't correctly added to the entity with the camera. You can see this by using A/D to move the camera. The expected behaviour is for it to rotate. The observed behaviour is strafing.

```javascript
import React from 'react';
import {Scene, Entity} from 'aframe-react';
import aframe from 'aframe';
import ReactDOM from 'react-dom';
import aframeExtras from 'aframe-extras';
import aframeKeyboardControls from 'aframe-keyboard-controls';

aframe.registerComponent('keyboard-controls', aframeKeyboardControls);
aframeExtras.primitives.registerAll(aframe);
aframeExtras.controls.registerAll(aframe);

const Catch = React.createClass({
  render() {
    return (
      <Scene className="scene">

        <Entity primitive="a-grid" position="0 0 0" />

        <Entity
          primitive="a-box"
          position="0 3 -2"
          width="0.5"
          height="0.5"
          depth="0.5"
          color="#EF2D5E"
        />

        <Entity
          camera="userHeight: 1.6"
          keyboard-controls="mode: fps"
          universal-controls="movementEnabled: false; rotationControls: hmd"
          position="0 1.6 4"
        />

      </Scene>
    );
  },
});

document.addEventListener('DOMContentLoaded', _ => {
  ReactDOM.render(<Catch />, document.querySelector('#catch-scene'));
});
```

### CODE REVIEW

**Comment by ngokevin** [comment]
> the position and rotation components have values that are NaN

Would it help to tell A-Frame React to render those as `0 0 0` rather than empty string?

**Comment by jesstelford** [comment]
Unfortunately I don't think it's that easy. The example above can be used with the physics system by adding the `dynamic-body` component to the `a-box`, which already has a `position` component set.

I've tried tracing through aframe, and through react, but I can't for the life of me find where exactly those `NaN`s are being set, and why it works fine with normal DOM, but not with `aframe-react` :/ (And the same goes for the camera components in the example above).

**Comment by jesstelford** [comment]
For now, I'm resorting to doing a `dangerouslySetInnerHTML`, and dumping the markup in there. It means manually managing the pieces of the scene still, but at least it's wrapped in a react component, so I can use it in the rest of my app.

**Comment by jesstelford** [comment]
Possibly related, [this discussion in slack](https://aframevr.slack.com/archives/learning/p1478552868239206):


ngokevin	[8:07 AM]  
the `NaN` is weird

jgl	[8:08 AM]  
Exactly, I thought it was as simple as having a single property schema, type: 'int', default: 2, and then be able to access that data by doing: var side = this.data; //should be 2, the default value as it says in the component docs:

[8:08]  
Yes

[8:08]  
@ngokevin Are you seeing the same error if you try to access: https://jgl.github.io/APieceOfArtAsBigAsIndia/terrainModelComponentWithMyComponent.html

[8:13]  
even if I just change my schema to: schema: { default: 2 }, i get the same result

[8:16]  
I’ve narrowed the code down to:

jgl	[8:20 AM]  
added a Plain Text snippet 
AFRAME.registerComponent('material-side-modifier', {
  // This component can be used multiple times
  multiple: true,
  // Allow material-side-modifier component a single property schema, of type int, defaulting to 2
  schema: { default: 2 },
  init: function () {
    console.log("Inside of init() of material-side-modifier");
    var side = this.data; //should be 2, the default value
    console.log("The value of this.data is ", this.data); //why isn't this reporting properly?
    console.log("The value of var side is ", side); //why isn't this reporting properly?
  }
});
Add Comment Collapse

jgl	[8:20 AM]  
Which is about as simple as I can make it

[8:20]  
It’s running live here: https://jgl.github.io/APieceOfArtAsBigAsIndia/terrainModelComponentWithMyComponent.html

**Comment by ngokevin** [comment]
The NaN has been fixed on A-Frame master branch.

**Comment by jesstelford** [comment]
Awesome!

I also noticed a subtle difference in the way that react renders the DOM vs regular dom, and the setup that aframe goes through.

In particular, the example I gave at the top (dealing with camera controls) doesn't work because the `wasd-controls` are added, which appear to overwrite the other keyboard controls.

This all happens in [`setupDefaultCamera`](https://github.com/aframevr/aframe/blob/bbc2f0325cdd3c4bd95a69ce4ce9705b0e6a041d/src/systems/camera.js#L26) - triggered by the `loaded` event of `a-scene`. When rendered in regular DOM, the conditional `sceneEl.camera` is true, because it already knows about the `camera` component being around. On the otherhand, in React, it appears that elements are [added to the DOM, _then_ their children are added](https://github.com/facebook/react/blob/e3131c1d55d6695c2f0966379535f88b813f912b/src/renderers/dom/stack/client/DOMLazyTree.js#L77-L78), meaning the scene's loaded event will trigger before any of the children have loaded, essentially inverting the process of registering primitives and components with aframe.

It seems like this might make aframe and react fundamentally incompatible :(

**Comment by RSpace** [comment]
> It seems like this might make aframe and react fundamentally incompatible :(

Really? No, this can be fixed, right @ngokevin ? (Reading this as I am myself trying to set `antialias=true` on the `<a-scene>` element, which, as per the conversation above, does not work.

**Comment by Jickelsen** [comment]
Does this seem to be solvable, @ngokevin and @jesstelford? I am currently evaluating Aframe and Aframe-React for two experimental projects but my initial impression was that there are a few inconsistencies in how the two systems work together that one needs to be aware of. This seems like a potential showstopper though?

If there's a possibility of joining a discussion on Slack or Gitter I'd greatly appreciate it!

**Comment by ngokevin** [comment]
I can create an #react channel on the Slack. The NaN should be fixed in A-Frame now. All other issues are solvable, but I haven't had time to get around to fixing various bugs.

**Comment by ngokevin** [comment]
I've rewritten aframe-react to run data through .setAttribute so data flow should much simpler and less buggy.

**Pull request closed without merging**
