### PR TITLE
Stringify arrays.

### PR DESCRIPTION
**Pull request by shea-hawkins**
Moved serializeComponents outside of entity so that it can be used by all classes, added check for array to serialize arrays. I think that helper functions should be moved into another file if another gets added.

### CODE REVIEW

**Comment by ngokevin** [comment]
Thanks! This will work for now. Later, I would like this to be smarter in how it serializes. We can inspect the component's schema and property types to decide how to best serialize.

**Comment by meta-meta** [comment]
beautiful!

**Comment by shea-hawkins** [comment]
@ngokevin Do you have an example of how it will use the schema to impact how it serializes? For instance, checking if the input data is oneOf ?

My understanding is that aframe-core will handle throws if invalid data is passed in.

**Comment by lennerd** [comment]
Any plans when to push these changes to a new version on npm?

**Pull request merged**
